//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntityFrameworkMySQL
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ChinookContext : DbContext
    {
        public ChinookContext()
            : base("name=ChinookContext")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<album> albums { get; set; }
        public virtual DbSet<artist> artists { get; set; }
        public virtual DbSet<customer> customers { get; set; }
        public virtual DbSet<employee> employees { get; set; }
        public virtual DbSet<genre> genres { get; set; }
        public virtual DbSet<invoice> invoices { get; set; }
        public virtual DbSet<invoiceline> invoicelines { get; set; }
        public virtual DbSet<mediatype> mediatypes { get; set; }
        public virtual DbSet<playlist> playlists { get; set; }
        public virtual DbSet<track> tracks { get; set; }
    }
}
